language: scala

# single test suite, non-parallel build.

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage test coverageReport

after_script:
  - SCALA_TARGET_DIRECTORY=target/scala-$(echo $TRAVIS_SCALA_VERSION | grep -o -P '^\d+\.\d+' '-')
  - ./cc-test-reporter format-coverage -t cobertura $SCALA_TARGET_DIRECTORY/coverage-report/cobertura.xml
  - ./cc-test-reporter upload-coverage
