language: scala

# single test suite, non-parallel build.

env:
  global:
    - CC_TEST_REPORTER_ID=cc0f0f3d386dd2df8f293da36c9b3f207d5f41e852e6eb507ec253ab3e4d690e

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - sbt clean coverage test coverageReport

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
