name: Scala CI

on: [push]

jobs:
  test_job:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        SCALA_VERSION: [2.12.8]
    steps:
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - uses: actions/checkout@v1

    - name: Before Install
      run: git fetch --tags
    - name: Install
      run: sbt ++${{ matrix.SCALA_VERSION }} compile

    - name: Download codeclimate test reporter
      run: |
        curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        chmod +x ./cc-test-reporter
    - name: Make codeclimate test reporter ready
      run: ./cc-test-reporter before-build

    - name: Run tests
      run: sbt ++${{ matrix.SCALA_VERSION }} clean coverage test coverageReport

    - name: Report to codeclimate
      env:
        SCALA_TARGET_DIRECTORY: target/scala-$(echo ${{ matrix.SCALA_VERSION }} | grep -o -P '^\d+\.\d+' '-') 
      run: |
       ./cc-test-reporter format-coverage -t $SCALA_TARGET_DIRECTORY/coverage-report/cobertura.xml
       ./cc-test-reporter upload-coverage
