name: Scala CI

on: [push]

jobs:
  test_job:
    runs-on: [ubuntu-latest, windows-latest, macOS-latest]
    strategy:
      matrix:
        SCALA_VERSION: [2.12]
    steps:
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - uses: actions/checkout@v1

    - name: Before Install
      run: git fetch --tags
    - name: Install
      run: sbt ++${{ matrix.SCALA_VERSION }} compile

    - name: Download codeclimate test reporter
      run: |
        curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        chmod +x ./cc-test-reporter
    - name: Make codeclimate test reporter ready
      run: ./cc-test-reporter before-build

    - name: Run tests
      run: sbt ++${{ matrix.SCALA_VERSION }} clean coverage test coverageReport

    - name: Report to codeclimate
      run: |
       ./cc-test-reporter format-coverage -t cobertura target/scala-2.12/coverage-report/cobertura.xml
       ./cc-test-reporter upload-coverage
