name: Scala CI

on: [push]

jobs:
  UnitTests:
    strategy:
      matrix:
        scala_version: [2.13.1, 2.13.0, 2.12.8]
    
    env:
      TRAVIS_SCALA_VERSION: ${{ matrix.scala_version }}

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Cache repositry
      uses: actions/cache@v1.0.3
      with:
        path: ~/.m2/repository/
        # An explicit key for restoring and saving the cache
        key: maven-repo

    - name: Install
      run: sbt ++$$TRAVIS_SCALA_VERSION compile

    - name: Run tests
      run: sbt ++$$TRAVIS_SCALA_VERSION test

  MutationTests:
    strategy:
      matrix:
        scala_version: [2.13.1, 2.13.0, 2.12.8]
    
    env:
      TRAVIS_SCALA_VERSION: ${{ matrix.scala_version }}

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Cache repositry
      uses: actions/cache@v1.0.3
      with:
        path: ~/.m2/repository/
        # An explicit key for restoring and saving the cache
        key: maven-repo

    - name: Install
      run: sbt ++$$TRAVIS_SCALA_VERSION compile

    - name: Run mutation tests
      run: sbt ++$$TRAVIS_SCALA_VERSION stryker

  FormattingTests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Run formatting checks
      run: sbt scalafmtSbtCheck
